name: Continuous integration

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run tests on chapter2 codes
        run: |
          cd chapter2
          python small_refactor.py
          python -m doctest first_step.py -v
